name: CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug, msvc-release]#, clang-debug]
        enable_steam: [false]
        include:
          - enable_steam: true
            configuration: msvc-release
    name: 'build-windows [${{ matrix.configuration}}, steam: ${{ matrix.enable_steam }}]'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
        cmakeAppendedArgs: '-DSTORM_ENABLE_STEAM=${{ matrix.enable_steam }}'
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: storm-engine.${{ matrix.configuration }}-steam-${{ matrix.enable_steam}}
        path: build\${{ matrix.configuration }}\bin
    - name: sentry-cli
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install @sentry/cli
    - run: ./node_modules/.bin/sentry-cli --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} upload-dif --org storm-devs --project storm-engine "build\${{ matrix.configuration }}\bin\engine.pdb"
